SELECT
	meet.meeting_key,
	meet.circuit_key,
	meet.country_key,
	meet.meeting_name,
	meet.meeting_official_name,
	meet.meeting_code,
	sess.session_key,
	sess.session_name,
	sess.session_type,
	meet.circuit_short_name,
	meet.country_code AS meeting_country_code,
	meet.country_name,
	meet.location,
	meet.date_start as meeting_date_start,
	sess.date_start as session_date_start,
	sess.date_end as session_date_end,
	sess.gmt_offset,
	driv.driver_number,
	driv.first_name,
	driv.last_name,
	driv.full_name,
	driv.broadcast_name,
	driv.country_code AS driver_country_code,
	driv.team_name,
	lap.lap_number,
	lap.date_start as lap_date_start,
	lap.duration_sector_1,
	lap.duration_sector_2,
	lap.duration_sector_3,
	lap.i1_speed,
	lap.i2_speed,
	lap.is_pit_out_lap,
	lap.lap_duration,
	lap.segments_sector_1,
	lap.segments_sector_2,
	lap.segments_sector_3,
	lap.st_speed
FROM
	{{ source('raw', 'all_meetings') }} AS meet
JOIN {{ source('raw', 'all_sessions') }} AS sess ON meet.meeting_key = sess.meeting_key
JOIN {{ source('raw', 'all_drivers') }} AS driv ON meet.meeting_key = driv.meeting_key AND sess.session_key = driv.session_key
JOIN {{ source('raw', 'all_laps') }} AS lap ON meet.meeting_key = lap.meeting_key AND sess.session_key = lap.session_key AND driv.driver_number = lap.driver_number